[package]
name = "icm-cli"
version = "0.1.0"
edition = "2021"
description = "Permanent memory for AI agents"
license = "MIT"
repository = "https://github.com/rtk-ai/icm"
keywords = ["memory", "ai-agents", "mcp", "llm", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "icm"
path = "src/main.rs"

[features]
default = ["embeddings"]
embeddings = ["icm-core/embeddings", "icm-mcp/embeddings"]
vendored-openssl = ["openssl/vendored"]

[dependencies]
icm-core = { path = "../icm-core" }
icm-store = { path = "../icm-store" }
icm-mcp = { path = "../icm-mcp" }
anyhow = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
directories = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
openssl = { version = "0.10", optional = true }
